services:
  scaffold:
    build:
      target: scaffold
  package-lock:
    build:
      target: package-lock
  deploy-debug:
    build:
      target: metro-build
  debug:
    build:
      target: metro
    ports:
      - ${METRO_PORT:-8081}:8081
  generate-keystore:
    build:
      target: keygen
  release:
    build:
      target: release
